[2025-07-17T21:19:30.123+0300] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: save_weather.save_weather manual__2025-07-17T18:19:19.357752+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
